### PR TITLE
Render run summaries correctly when there are fewer percentiles than expected

### LINKED ISSUE #37: Summary is incorrect when there are fewer percentiles than expected
When a probe has fewer percentiles than expected for the number of benchmark iterations (perhaps it is not invoked once for every iteration) it renders like:
```
-------------------------------- SUMMARY (B) us ----------------------------------------------------
Percentile   run1         run2         run3      % Variation
50.0:            0.10         0.10         0.10         0.00
90.0:            0.10         0.10         0.10         0.00
99.0:            0.10         0.10         0.10         0.00
99.7:            0.10         0.10         0.10         0.00
worst:       Infinity     Infinity     Infinity    -Infinity
----------------------------------------------------------------------------------------------------
```
When in fact it should render like
```
-------------------------------- SUMMARY (B) us ----------------------------------------------------
Percentile   run1         run2         run3      % Variation
50.0:            0.10         0.10         0.10         0.00
90.0:            0.10         0.10         0.10         0.00
99.0:            0.10         0.10         0.10         0.00
worst:           0.10         0.10         0.10         0.00
----------------------------------------------------------------------------------------------------
```
i.e. it is the 99.7th percentile missing due to small sample size, not the "worst" measurement

### PR DESCRIPTION
**Pull request by nicktindall**
Fixes #37

### CODE REVIEW

**Review by JerryShea — APPROVED** [review]

File: src/main/java/net/openhft/chronicle/jlbh/PercentileSummary.java [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+ * <p>
+ * Handle runs with differing number of samples (and hence, percentiles) correctly
+ */
+public class PercentileSummary {
+
+    private final boolean skipFirst;
+    private final List<double[]> percentileRuns;
+    private final double[] percentiles;
+
+    public PercentileSummary(boolean skipFirst,
```
Comment (JerryShea) [inline src/main/java/net/openhft/chronicle/jlbh/PercentileSummary.java:25]: nice cleanup

Comment (JerryShea) [reply src/main/java/net/openhft/chronicle/jlbh/PercentileSummary.java:25]: Would it be possible to use this to get rid of TeamCityHelper.shortenArray?

Comment (nicktindall) [reply src/main/java/net/openhft/chronicle/jlbh/PercentileSummary.java:25]: I will look into that

File: src/main/java/net/openhft/chronicle/jlbh/PercentileSummary.java [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+import org.jetbrains.annotations.NotNull;
+
+import java.util.List;
+
+/**
+ * Calculates values for the run summary.
+ * <p>
+ * Handle runs with differing number of samples (and hence, percentiles) correctly
+ */
+public class PercentileSummary {
```
Comment (minborg) [inline src/main/java/net/openhft/chronicle/jlbh/PercentileSummary.java]: Guess which keyword I would like to see here... :-)

**Review by minborg — APPROVED** [review]

File: src/main/java/net/openhft/chronicle/jlbh/PercentileSummary.java (hunk 1 above)
Comment (nicktindall) [reply src/main/java/net/openhft/chronicle/jlbh/PercentileSummary.java:25]: Done

File: src/main/java/net/openhft/chronicle/jlbh/TeamCityHelper.java [hunk 3]
```diff
@@ -13,11 +14,6 @@
     private TeamCityHelper() {
     }
 
-    public static void histo(@NotNull String name, @NotNull Histogram histo, @NotNull PrintStream printStream) {
-        double[] percentages = Histogram.percentilesFor(histo.totalCount());
-        printPercentiles(name, printStream, percentages, histo.getPercentiles());
-    }
-
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/jlbh/TeamCityHelper.java]: This didn't seem to be used anywhere?

File: src/test/java/net/openhft/chronicle/jlbh/JLBHTest.java [hunk 4]
```diff
@@ -207,6 +204,27 @@ public void teamCityHelper() {
...
+        start(jlbh);
+
+        System.out.println(baos);
+        assertTrue(baos.toString().contains(
+                "-------------------------------- SUMMARY (B) us ----------------------------------------------------\n" +
+                "Percentile   run1         run2         run3      % Variation\n" +
+                "50.0:            0.10         0.10         0.10         0.00\n" +
+                "90.0:            0.10         0.10         0.10         0.00\n" +
+                "99.0:            0.10         0.10         0.10         0.00\n" +
+                "worst:           0.10         0.10         0.10         0.00"));
```
Comment (nicktindall) [inline src/test/java/net/openhft/chronicle/jlbh/JLBHTest.java:225]: It now omits rows that are all `Infinity`

File: src/main/java/net/openhft/chronicle/jlbh/TeamCityHelper.java (hunk 3 above)
Comment (JerryShea) [reply src/main/java/net/openhft/chronicle/jlbh/TeamCityHelper.java]: Could be used somewhere else. I thought it might be useful, but can't remember if it is used
